const $=id=>document.getElementById(id);
let latest=null, displayed=null, ws=null, sequence=0, sending=false, paused=false, selection=null;
const headers=()=>({'Authorization':'Bearer '+$('token').value,'Content-Type':'application/json'});
async function api(path,body){const r=await fetch('/api/'+path,{headers:headers(),method:body?'POST':'GET',body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error((await r.json()).detail||r.status);return r.json()}
function paint(){if(!displayed)return;const canvas=$('overlay');canvas.width=displayed.width;canvas.height=displayed.height;const c=canvas.getContext('2d');if($('heat').checked){displayed.depth_m.forEach((z,i)=>{if(z==null)return;c.fillStyle=`hsla(${Math.min(220,z/8*220)},75%,52%,0.38)`;c.fillRect(i%80*canvas.width/80,Math.floor(i/80)*canvas.height/45,canvas.width/80+1,canvas.height/45+1)})}if(selection){c.strokeStyle='white';c.lineWidth=2;c.beginPath();c.arc(selection.u*canvas.width,selection.v*canvas.height,8,0,Math.PI*2);c.stroke()}}
async function poll(){if(document.hidden||paused){setTimeout(poll,250);return}try{latest=await api('snapshot');const current=latest;const decoded=new Image();decoded.src='data:image/jpeg;base64,'+current.preview_jpeg;await decoded.decode();$('preview').src=decoded.src;displayed=current;paint();$('status').textContent=current.source==='mock'?'模拟相机已连接':'ZED 已连接';$('frame').textContent=`FRAME ${current.frame_id} · ${current.age_ms} ms`;$('near').textContent=current.near_m==null?'无有效数据':current.near_m.toFixed(2)+' m';$('valid').textContent=(current.valid_fraction*100).toFixed(0)+'%';$('warning').textContent=current.near_warning?'近距离区域提示':'中心区域未触发近距离提示'}catch(e){displayed=null;$('status').textContent='连接异常';$('measure').textContent=e.message;stop()}setTimeout(poll,180)}
$('preview').onclick=async e=>{if(!displayed)return;const r=e.target.getBoundingClientRect();selection={u:(e.clientX-r.left)/r.width,v:(e.clientY-r.top)/r.height};const frame=displayed;paint();try{const m=await api('depth/measure',{frame_id:frame.frame_id,...selection});$('measure').textContent=m.valid?`帧 ${m.frame_id} · 直线距离 ${m.range_m.toFixed(2)} m · 轴向深度 ${m.axial_m.toFixed(2)} m`:'此位置没有可信深度'}catch(e){$('measure').textContent='画面已过期，请重新选择：'+e.message}};
$('heat').onchange=paint;
for(const axis of ['yaw','pitch'])$(axis).oninput=()=>$(axis+'Value').textContent=$(axis).value+'°';
function stop(){if(ws){ws.close();ws=null}$('control').disabled=false;$('release').disabled=true;$('controlStatus').textContent='控制已停止';sending=false}
$('control').onclick=()=>{if(ws)return;sequence=0;const socket=new WebSocket(location.origin.replace(/^http/,'ws')+'/api/control');ws=socket;$('control').disabled=true;socket.onopen=()=>socket.send(JSON.stringify({token:$('token').value}));socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.error){stop();$('controlStatus').textContent=m.error;return}if(m.type==='lease'){for(const axis of ['yaw','pitch']){$(axis).value=m[axis+'_deg'];$(axis+'Value').textContent=Number(m[axis+'_deg']).toFixed(1)+'°'}sending=true;$('release').disabled=false}if(m.type==='ack')$('controlStatus').textContent=`当前：水平 ${m.yaw_deg.toFixed(1)}° / 俯仰 ${m.pitch_deg.toFixed(1)}°`;};socket.onclose=()=>{if(ws===socket)stop()};socket.onerror=()=>{stop();$('controlStatus').textContent='控制连接失败'}};
setInterval(()=>{if(ws?.readyState===1&&sending)ws.send(JSON.stringify({sequence:sequence++,yaw_deg:+$('yaw').value,pitch_deg:+$('pitch').value}))},100);
$('release').onclick=stop;$('reconnect').onclick=()=>{$('status').textContent='重新连接中';stop()};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});window.addEventListener('pagehide',stop);
$('loadVideo').onclick=()=>{try{const url=new URL($('videoURL').value);if(!['http:','https:'].includes(url.protocol))throw Error('请输入 HTTP 或 HTTPS 地址');$('video').src=url.href;$('video').play().catch(e=>$('videoError').textContent=e.message)}catch(e){$('videoError').textContent=e.message}};
$('video').onerror=()=>$('videoError').textContent='无法播放此地址或当前浏览器不支持该格式。';poll();
